version: "3.4"
services:
  api:
    build:
      context: ./api
      network: host
    volumes:
      - ./api:/usr/src/app
    networks:
      - front
    ports:
      - "8881:80"

  frontend:
    build:
      context: ./client
    restart: always
    build: ./client
    ports:
      - "8882:80"
    networks:
      - front
    depends_on:
      - api


networks:
  front:
    driver: bridge

volumes:
  blogpg:
